<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currencies')->truncate();

        $currency = [
            ['name' => 'USD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'EUR', 'unicode' => '&#8364;', 'symbol' => '€'],
            ['name' => 'GBP', 'unicode' => '&#163;', 'symbol' => '£'],
            ['name' => 'JPY', 'unicode' => '&#165;', 'symbol' => '¥'],
            ['name' => 'AUD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'CAD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'CHF', 'unicode' => '&#67;&#72;&#70;', 'symbol' => 'CHF'],
            ['name' => 'CNY', 'unicode' => '&#165;', 'symbol' => '¥'],
            ['name' => 'HKD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'NZD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'SEK', 'unicode' => '&#107;&#114;', 'symbol' => 'kr'],
            ['name' => 'KRW', 'unicode' => '&#8361;', 'symbol' => '₩'],
            ['name' => 'SGD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'NOK', 'unicode' => '&#107;&#114;', 'symbol' => 'kr'],
            ['name' => 'MXN', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'INR', 'unicode' => '&#8377;', 'symbol' => '₹'],
            ['name' => 'BRL', 'unicode' => '&#82;&#36;', 'symbol' => 'R$'],
            ['name' => 'RUB', 'unicode' => '&#8381;', 'symbol' => '₽'],
            ['name' => 'ZAR', 'unicode' => '&#82;', 'symbol' => 'R'],
            ['name' => 'TRY', 'unicode' => '&#8378;', 'symbol' => '₺'],
            ['name' => 'TWD', 'unicode' => '&#78;&#84;&#36;', 'symbol' => 'NT$'],
            ['name' => 'DKK', 'unicode' => '&#107;&#114;', 'symbol' => 'kr'],
            ['name' => 'PLN', 'unicode' => '&#122;&#322;', 'symbol' => 'zł'],
            ['name' => 'THB', 'unicode' => '&#3647;', 'symbol' => '฿'],
            ['name' => 'IDR', 'unicode' => '&#82;&#112;', 'symbol' => 'Rp'],
            ['name' => 'HUF', 'unicode' => '&#70;&#116;', 'symbol' => 'Ft'],
            ['name' => 'CZK', 'unicode' => '&#75;&#269;', 'symbol' => 'Kč'],
            ['name' => 'ILS', 'unicode' => '&#8362;', 'symbol' => '₪'],
            ['name' => 'CLP', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'PHP', 'unicode' => '&#8369;', 'symbol' => '₱'],
            ['name' => 'AED', 'unicode' => '&#1583;.&#1573;', 'symbol' => 'د.إ'],
            ['name' => 'COP', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'SAR', 'unicode' => '&#1585;.&#1587;', 'symbol' => '﷼'],
            ['name' => 'MYR', 'unicode' => '&#82;&#77;', 'symbol' => 'RM'],
            ['name' => 'RON', 'unicode' => '&#108;&#101;&#105;', 'symbol' => 'lei'],
            ['name' => 'AFN', 'unicode' => '&#1547;', 'symbol' => '؋'],
            ['name' => 'ALL', 'unicode' => '&#76;&#101;&#107;', 'symbol' => 'Lek'],
            ['name' => 'DZD', 'unicode' => '&#1583;.&#1580;', 'symbol' => 'د.ج'],
            ['name' => 'AOA', 'unicode' => '&#75;&#122;', 'symbol' => 'Kz'],
            ['name' => 'ARS', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'AMD', 'unicode' => '&#1423;', 'symbol' => '֏'],
            ['name' => 'AWG', 'unicode' => '&#402;', 'symbol' => 'ƒ'],
            ['name' => 'AZN', 'unicode' => '&#8380;', 'symbol' => '₼'],
            ['name' => 'BSD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'BHD', 'unicode' => '&#1583;.&#1576;', 'symbol' => '.د.ب'],
            ['name' => 'BDT', 'unicode' => '&#2547;', 'symbol' => '৳'],
            ['name' => 'BBD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'BYN', 'unicode' => '&#66;&#114;', 'symbol' => 'Br'],
            ['name' => 'BZE', 'unicode' => '&#66;&#90;&#36;', 'symbol' => 'BZ$'],
            ['name' => 'BMD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'BTN', 'unicode' => '&#78;&#117;&#46;', 'symbol' => 'Nu.'],
            ['name' => 'BOB', 'unicode' => '&#36;&#98;', 'symbol' => 'Bs.'],
            ['name' => 'BAM', 'unicode' => '&#75;&#77;', 'symbol' => 'KM'],
            ['name' => 'BWP', 'unicode' => '&#80;', 'symbol' => 'P'],
            ['name' => 'BND', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'BGN', 'unicode' => '&#1083;&#1074;', 'symbol' => 'лв'],
            ['name' => 'BIF', 'unicode' => '&#70;&#66;&#117;', 'symbol' => 'FBu'],
            ['name' => 'KHR', 'unicode' => '&#6107;', 'symbol' => '៛'],
            ['name' => 'CVE', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'KYD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'XAF', 'unicode' => '&#70;&#67;&#70;&#65;', 'symbol' => 'FCFA'],
            ['name' => 'XPF', 'unicode' => '&#80;', 'symbol' => 'P'],
            ['name' => 'KMF', 'unicode' => '&#67;&#70;', 'symbol' => 'CF'],
            ['name' => 'CDF', 'unicode' => '&#70;&#67;', 'symbol' => 'FC'],
            ['name' => 'CRC', 'unicode' => '&#8353;', 'symbol' => '₡'],
            ['name' => 'HRK', 'unicode' => '&#107;&#110;', 'symbol' => 'kn'],
            ['name' => 'CUP', 'unicode' => '&#8369;', 'symbol' => '₱'],
            ['name' => 'DJF', 'unicode' => '&#70;&#100;&#106;', 'symbol' => 'Fdj'],
            ['name' => 'DOP', 'unicode' => '&#82;&#68;&#36;', 'symbol' => 'RD$'],
            ['name' => 'EGP', 'unicode' => '&#163;', 'symbol' => '£'],
            ['name' => 'ERN', 'unicode' => '&#78;&#102;&#107;', 'symbol' => 'Nfk'],
            ['name' => 'ETB', 'unicode' => '&#66;&#114;', 'symbol' => 'Br'],
            ['name' => 'FKP', 'unicode' => '&#163;', 'symbol' => '£'],
            ['name' => 'FJD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'GMD', 'unicode' => '&#68;', 'symbol' => 'D'],
            ['name' => 'GEL', 'unicode' => '&#8382;', 'symbol' => '₾'],
            ['name' => 'GHS', 'unicode' => '&#8373;', 'symbol' => '₵'],
            ['name' => 'GIP', 'unicode' => '&#163;', 'symbol' => '£'],
            ['name' => 'GTQ', 'unicode' => '&#81;', 'symbol' => 'Q'],
            ['name' => 'GNF', 'unicode' => '&#70;&#71;', 'symbol' => 'FG'],
            ['name' => 'GYD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'HTG', 'unicode' => '&#71;', 'symbol' => 'G'],
            ['name' => 'HNL', 'unicode' => '&#76;', 'symbol' => 'L'],
            ['name' => 'ISK', 'unicode' => '&#107;&#114;', 'symbol' => 'kr'],
            ['name' => 'IRR', 'unicode' => '&#65020;', 'symbol' => '﷼'],
            ['name' => 'IQD', 'unicode' => '&#1593;.&#1583;', 'symbol' => 'ع.د'],
            ['name' => 'JMD', 'unicode' => '&#74;&#36;', 'symbol' => 'J$'],
            ['name' => 'JOD', 'unicode' => '&#1583;.&#1575;', 'symbol' => 'د.ا'],
            ['name' => 'KZT', 'unicode' => '&#8376;', 'symbol' => '₸'],
            ['name' => 'KES', 'unicode' => '&#75;&#83;&#104;', 'symbol' => 'KSh'],
            ['name' => 'KWD', 'unicode' => '&#1583;.&#1082;', 'symbol' => 'د.ك'],
            ['name' => 'KGS', 'unicode' => '&#1083;&#1074;', 'symbol' => 'лв'],
            ['name' => 'LAK', 'unicode' => '&#8365;', 'symbol' => '₭'],
            ['name' => 'LBP', 'unicode' => '&#163;', 'symbol' => 'ل.ل'],
            ['name' => 'LSL', 'unicode' => '&#76;', 'symbol' => 'L'],
            ['name' => 'LRD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'LYD', 'unicode' => '&#1083;.&#1076;', 'symbol' => 'ل.د'],
            ['name' => 'MOP', 'unicode' => '&#77;&#79;&#80;&#36;', 'symbol' => 'MOP$'],
            ['name' => 'MKD', 'unicode' => '&#1076;&#1077;&#1085;', 'symbol' => 'ден'],
            ['name' => 'MGA', 'unicode' => '&#65;&#114;', 'symbol' => 'Ar'],
            ['name' => 'MWK', 'unicode' => '&#77;&#75;', 'symbol' => 'MK'],
            ['name' => 'MVR', 'unicode' => '&#1083;&#1091;&#1092;', 'symbol' => '.ރ'],
            ['name' => 'MRO', 'unicode' => '&#85;&#77;', 'symbol' => 'UM'],
            ['name' => 'MUR', 'unicode' => '&#8360;', 'symbol' => '₨'],
            ['name' => 'MDL', 'unicode' => '&#76;', 'symbol' => 'L'],
            ['name' => 'MNT', 'unicode' => '&#8366;', 'symbol' => '₮'],
            ['name' => 'MAD', 'unicode' => '&#1583;.&#1605;.', 'symbol' => 'د.م.'],
            ['name' => 'MZN', 'unicode' => '&#77;&#84;', 'symbol' => 'MT'],
            ['name' => 'MMK', 'unicode' => '&#75;', 'symbol' => 'K'],
            ['name' => 'NAD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'NPR', 'unicode' => '&#8360;', 'symbol' => '₨'],
            ['name' => 'ANG', 'unicode' => '&#402;', 'symbol' => 'ƒ'],
            ['name' => 'NIO', 'unicode' => '&#67;&#36;', 'symbol' => 'C$'],
            ['name' => 'NGN', 'unicode' => '&#8358;', 'symbol' => '₦'],
            ['name' => 'KPW', 'unicode' => '&#8361;', 'symbol' => '₩'],
            ['name' => 'OMR', 'unicode' => '&#65020;', 'symbol' => '﷼'],
            ['name' => 'PKR', 'unicode' => '&#8360;', 'symbol' => '₨'],
            ['name' => 'PAB', 'unicode' => '&#66;&#47;&#46;', 'symbol' => 'B/.'],
            ['name' => 'PGK', 'unicode' => '&#75;', 'symbol' => 'K'],
            ['name' => 'PYG', 'unicode' => '&#71;&#115;', 'symbol' => 'Gs'],
            ['name' => 'PEN', 'unicode' => '&#83;.&#47;', 'symbol' => 'S/.'],
            ['name' => 'QAR', 'unicode' => '&#1585;.&#1602;', 'symbol' => '﷼'],
            ['name' => 'RWF', 'unicode' => '&#82;&#70;&#119;', 'symbol' => 'RFw'],
            ['name' => 'SHP', 'unicode' => '&#163;', 'symbol' => '£'],
            ['name' => 'WST', 'unicode' => '&#84;&#36;', 'symbol' => 'T$'],
            ['name' => 'STD', 'unicode' => '&#68;&#98;', 'symbol' => 'Db'],
            ['name' => 'SCR', 'unicode' => '&#8360;', 'symbol' => '₨'],
            ['name' => 'SLL', 'unicode' => '&#76;&#101;', 'symbol' => 'Le'],
            ['name' => 'SBD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'SOS', 'unicode' => '&#83;', 'symbol' => 'S'],
            ['name' => 'LKR', 'unicode' => '&#8360;', 'symbol' => '₨'],
            ['name' => 'SDG', 'unicode' => '&#163;', 'symbol' => '£'],
            ['name' => 'SRD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'SZL', 'unicode' => '&#76;', 'symbol' => 'L'],
            ['name' => 'SYP', 'unicode' => '&#163;', 'symbol' => '£'],
            ['name' => 'TJS', 'unicode' => '&#84;&#74;&#83;', 'symbol' => 'TJS'],
            ['name' => 'TZS', 'unicode' => '&#84;&#83;&#104;', 'symbol' => 'TSh'],
            ['name' => 'TOP', 'unicode' => '&#84;&#36;', 'symbol' => 'T$'],
            ['name' => 'TTD', 'unicode' => '&#84;&#84;&#36;', 'symbol' => 'TT$'],
            ['name' => 'TND', 'unicode' => '&#1583;.&#1578;', 'symbol' => 'د.ت'],
            ['name' => 'TMT', 'unicode' => '&#109;', 'symbol' => 'm'],
            ['name' => 'UGX', 'unicode' => '&#85;&#83;&#104;', 'symbol' => 'USh'],
            ['name' => 'UAH', 'unicode' => '&#8372;', 'symbol' => '₴'],
            ['name' => 'UYU', 'unicode' => '&#36;&#85;', 'symbol' => '$U'],
            ['name' => 'UZS', 'unicode' => '&#1083;&#1074;', 'symbol' => 'лв'],
            ['name' => 'VUV', 'unicode' => '&#86;&#84;', 'symbol' => 'VT'],
            ['name' => 'VEF', 'unicode' => '&#66;&#115;', 'symbol' => 'Bs'],
            ['name' => 'VND', 'unicode' => '&#8363;', 'symbol' => '₫'],
            ['name' => 'YER', 'unicode' => '&#65020;', 'symbol' => '﷼'],
            ['name' => 'ZMW', 'unicode' => '&#90;&#75;', 'symbol' => 'ZK'],
            ['name' => 'ZWL', 'unicode' => '&#90;&#36;', 'symbol' => '$'],
            ['name' => 'XOF', 'unicode' => '&#67;&#70;&#65;', 'symbol' => 'CFA'],
            ['name' => 'XCD', 'unicode' => '&#36;', 'symbol' => '$'],
            ['name' => 'XDR', 'unicode' => '&#83;&#68;&#82;', 'symbol' => 'SDR'],
            ['name' => 'XAU', 'unicode' => '&#111;&#122;', 'symbol' => 'oz'],
            ['name' => 'XAG', 'unicode' => '&#111;&#122;', 'symbol' => 'oz'],
            ['name' => 'XPT', 'unicode' => '&#111;&#122;', 'symbol' => 'oz'],
            ['name' => 'XPD', 'unicode' => '&#111;&#122;', 'symbol' => 'oz'],
        ];

        foreach ($currency as $data) {
            Currency::create($data);
        }
    }
}
