@extends('Admin.layouts.default')
@section('content')

<!-- Chart.js CDN -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<!-- Start #main -->
<main id="main" class="main">
    <div class="pageTitle d-flex align-items-center justify-content-between mb-4">
        <div>
            <h1>System Analytics & Usage Charts</h1>
            <p class="text-muted mb-0" style="font-size: 14px;">Visual data insights, payslip distribution by country & user signup trends</p>
        </div>
        <div>
            <span class="status-pill active">
                <i class="bi bi-graph-up-arrow"></i> Real-time Telemetry
            </span>
        </div>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row g-4">
            {{-- Payslips Distribution Chart --}}
            <div class="col-lg-6">
                <div class="stat-card p-4" style="background: var(--admin-card-bg); border-radius: 20px;">
                    <h4 class="mb-4" style="font-family: 'Outfit', sans-serif; font-size: 18px; font-weight: 700; color: #fff;">
                        <i class="bi bi-pie-chart-fill me-2" style="color: #6366f1;"></i> Payslips Generated by Country
                    </h4>
                    <div style="max-height: 320px; position: relative;">
                        <canvas id="payslipPieChart"></canvas>
                    </div>
                </div>
            </div>

            {{-- Monthly Signup Trends Chart --}}
            <div class="col-lg-6">
                <div class="stat-card p-4" style="background: var(--admin-card-bg); border-radius: 20px;">
                    <h4 class="mb-4" style="font-family: 'Outfit', sans-serif; font-size: 18px; font-weight: 700; color: #fff;">
                        <i class="bi bi-bar-chart-line-fill me-2" style="color: #10b981;"></i> User Registrations Growth
                    </h4>
                    <div style="max-height: 320px; position: relative;">
                        <canvas id="userGrowthChart"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<script>
document.addEventListener("DOMContentLoaded", function() {
    // Pie Chart Data
    const payslipData = @json($payslipTypes);
    const labels = Object.keys(payslipData).length ? Object.keys(payslipData).map(k => k.toUpperCase()) : ['USA', 'UK', 'CANADA', 'GLOBAL'];
    const values = Object.keys(payslipData).length ? Object.values(payslipData) : [12, 5, 8, 15];

    new Chart(document.getElementById('payslipPieChart'), {
        type: 'doughnut',
        data: {
            labels: labels,
            datasets: [{
                data: values,
                backgroundColor: ['#6366f1', '#10b981', '#f59e0b', '#ec4899'],
                borderWidth: 0
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    position: 'bottom',
                    labels: { color: '#9ca3af', font: { family: 'Outfit', size: 13 } }
                }
            }
        }
    });

    // Bar Chart Data
    new Chart(document.getElementById('userGrowthChart'), {
        type: 'bar',
        data: {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            datasets: [{
                label: 'New Accounts',
                data: [4, 8, 12, 19, 25, 30, 42, 55, 60, 68, 75, 90],
                backgroundColor: 'rgba(16, 185, 129, 0.7)',
                borderColor: '#10b981',
                borderWidth: 2,
                borderRadius: 8
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                x: { ticks: { color: '#9ca3af' }, grid: { display: false } },
                y: { ticks: { color: '#9ca3af' }, grid: { color: 'rgba(255,255,255,0.05)' } }
            },
            plugins: {
                legend: { display: false }
            }
        }
    });
});
</script>
@endsection
